diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
gui.recentrepo=E:/programming projects/RamadanApp/src
safe.directory=/RamadanApp
safe.directory=E:\programming projects\RamadanApp
user.name=EltayebIbrahim
user.email=tayeb1293@yahoo.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.autocrlf=false
user.name=tayeb1293
user.email=tayeb1293@yahoo.com
remote.origin.url=https://github.com/tayeb1293/Ramadan_App.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
